# -*- coding: utf-8 -*-
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['resources/c_number', 'resources/mapping_table', 'resources/zhconv', 'resources/fonts', 'resources/Img']
OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'Img/MDCx.icns',
    'plist': {
        'CFBundleName': "MDCx",  # app名字
        'CFBundleDisplayName': "MDCx",
        'CFBundleGetInfoString': "MDCx",
        'CFBundleIdentifier': "MDCx",  # 进程名字
        'CFBundleVersion': "20231005",
        'CFBundleShortVersionString': "20231005",  # 版本号
        'NSHumanReadableCopyright': u"版权所有 © 2023",
        'Localization native development region': '',
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'lxml', 'pyquery', 'cloudscraper', 'requests', 'beautifulsoup4', 'Pillow', 'PyQt5',
                    'PySocks', 'urllib3', 'zhconv', 'langid', 'AppKit', 'deepl-translate', 'ping3', 'curl_cffi'],
)
